"""Render the latest teacher-independent support screen and scoped decision."""
import sys,time,collections
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
import numpy as np
from scripts.decota_matrix_common_v1 import read,write,load,sha
from scripts.run_tastvg_native_spatial_rollout_s05_v1 import OUT,S0,verify
from scripts.audit_tastvg_native_spatial_rollout_public_v1 import run as audit

def run():
    lock=verify();s=read(OUT/'SUMMARY.json');rows=read(OUT/'ROWS.json');prior=read(S0/'SUMMARY.json');state=load(OUT/'PARAMETER_SUPPORT.pt');cfg=read(OUT/'PARAMETER_SUPPORT.json');assert sha(OUT/'PARAMETER_SUPPORT.pt')==cfg['sha256']
    flat=lambda x:np.concatenate([v.double().numpy().ravel() for v in x.values()]);center=flat(state['center']);basis=state['basis'].numpy();np.testing.assert_allclose(basis@basis.T,np.eye(4),atol=1e-12,rtol=0)
    for k in range(4):
        for sign,j in [(1,1+2*k),(-1,2+2*k)]:np.testing.assert_allclose(flat(state['states'][j])-center,sign*cfg['radius']*basis[k],atol=1.5e-7,rtol=0)
    write(OUT/'PARAMETER_AUDIT.json',dict(status='pass',states=9,orthogonal_pairs=4,cast_absolute_tolerance=1.5e-7,expert_independent_seed=20260929))
    write(OUT/'PUBLIC_AUDIT.json',audit(OUT,S0));alloc=[read(f) for f in (OUT/'allocations').glob('*.json')];res=dict(gpu_process_seconds=sum(a['seconds'] for a in alloc),new_expert_calls=0,backward_calls=0,new_backbone_captures=0,candidates=864,full_reinsertion_cells=2,gpu_failures=sum(a['status']=='failed' for a in alloc),scoring_serialization_recovery=read(OUT/'SCORING_RECOVERY.json'))
    write(OUT/'RESOURCES.json',res);pr=read(S0/'PROVENANCE.json');write(OUT/'PROVENANCE.json',dict(backbone='TA-STVG',source_checkpoint=pr['source_checkpoint'],source_model_state_sha256=pr['source_model_state_sha256'],cohort=pr['cohort'],sources=16,queries=16,cells=96,conditions=lock['conditions'],pins=lock['pins'],prior_barriers=lock['prior_barriers'],GT_scope='Same16 previously exposed keys, post-seal offline scoring only',expert_data_read_during_generation=False,online_learning_performed=False,production_changed=False))
    pp=lambda v:f'{100*v:.4f}';ci=lambda x:'['+', '.join(pp(v) for v in x['ci95'])+']'
    lines=['# S0.5 — Native Spatial Rollout Support Test','', 'Completed / audited. Teacher-independent parameter rollouts produce limited support at this one fixed radius. Do not advance this configuration to S1 on the measured headroom; no OPD or online learning was run.','', '| Group | Native sIoU % | Six-layer oracle gain pp | 9-rollout oracle gain pp | Six-layer + rollout union gain pp | S0 union gain pp | New union − S0 union pp (95% CI) |','|---|---:|---:|---:|---:|---:|---|']
    for g in ['corruption']+lock['conditions']:
        m=s[g]['metrics'];old=prior[g]['metrics'];lines.append(f"| {g} | {pp(m['native_s']['mean'])} | {pp(m['six_layer_gain']['mean'])} | {pp(m['rollout_gain']['mean'])} | {pp(m['union_gain']['mean'])} | {pp(old['union_oracle_s']['mean']-old['native_s']['mean'])} | {pp(m['union_minus_s0']['mean'])} {ci(m['union_minus_s0'])} |")
    lines+=['','## What was actually tested','', 'Same16 original C3 historically exposed VidSTG parent sources, one query/source, clean and five existing source-hash seed0 transient5% corruptions:96cells. Frozen source VidSTG TA-STVG checkpoint, exact native H caches. Parameter interface1792: second-pass spatial query residual256 and final spatial block5 norm1/norm3/norm4 weight+bias1536. LN changes apply on both native calls; every candidate restores the source model. H, text, motion and other parameters are not updated. Original dynamic suffix is recomputed.','',f"Four orthonormal Gaussian-QR directions, seed20260929, fixed across every source/condition; plus/minus pairs and native center yield9 candidates. One radius: .05 times the initial full parameter norm {cfg['central_norm']:.8f}, giving absolute L2 radius {cfg['radius']:.8f}. This parameter radius is unrelated to old .004 H steps. No radius/direction-count sweep. Source parameters determine the scale; neither teacher outputs nor GT do. All96 cells have9 distinct tube boxes.",'', 'The worker rejects expert caches, propagation outputs and GT files.864 complete candidate tubes and parameter states are sealed before GT scoring. The existing interface can hold persistent parameters, but this support screen uses the same unlearned central state on every arrival. This does not establish online transfer. No expert ranking, optimizer, backward pass or pseudo-box regression enters generation.','', 'The oracle selects one whole candidate tube using sIoU on all GT-valid sampled frames, never a frame-wise mixture. Native is retained, so nonnegative oracle gain is structural. Six-layer union contains15 entries including duplicated native (at most14 distinct); new rollouts are9 distinct within each cell. Compare union to the same-cohort S0 union1.3886pp; do not compare9-vs6 candidate counts as a controlled mechanism isolation. Five corruption conditions average within source, then source macro;10000 source bootstrap draws seed20260929. Descriptive exposed-development evidence, not independent confirmation.','', '## Secondary transfer and fixed-arm behavior','']
    for g in ['corruption','clean']:
        m=s[g]['metrics'];lines.append(f"{g}: whole-tube oracle gain {pp(m['rollout_gain']['mean'])}pp CI{ci(m['rollout_gain'])}; union gain {pp(m['union_gain']['mean'])}pp CI{ci(m['union_gain'])}. Unobserved positions gain at whole-tube oracle: matched12 {pp(m['matched12_unobserved_gain']['mean'])}pp CI{ci(m['matched12_unobserved_gain'])}; all16 {pp(m['unobserved_gain']['mean'])}pp. Same deterministic five uniform positions as S0, without reading masks. Observed gain {pp(m['observed_gain']['mean'])}pp (12sources). Mean per-source minimum candidate self-sIoU {pp(m['minimum_self_sIoU']['mean'])}%.")
    lines+=['','| Fixed arm | Corruption Δs pp | 95% CI pp | Sources better / worse (>0.1pp) | Sources worse >5pp |','|---|---:|---|---|---:|']
    for k,a in s['corruption']['fixed_arms'].items():lines.append(f"| {k} | {pp(a['gain']['mean'])} | {ci(a['gain'])} | {a['sources_better']} / {a['sources_worse']} | {a['sources_worse_gt5pp']} |")
    lines+=['','| Source | Rollout oracle gain pp | Union gain pp | Union change vs S0 pp |','|---|---:|---:|---:|']
    for p in sorted({r['parent'] for r in rows}):
        rr=[r for r in rows if r['parent']==p and r['condition']!='clean'];lines.append(f"| Q{p+1:02} | "+' | '.join(pp(np.mean([r[k] for r in rr])) for k in ['rollout_gain','union_gain','union_minus_s0'])+' |')
    lines+=['','## Decision and boundaries','', 'The current9-candidate/.05-radius parameter neighborhood does not materially open the old1.39pp union support: its union is1.2441pp, paired difference−.1444pp with CI spanning zero. This is well below the user’s illustrative3–5pp scale. Do not start S1 critic/Reverse-KL from this screen, and do not automatically widen radius or add a sweep. Preserve the positive rollout cases and unobserved gains. This bounded result does not prove that spatial OPD, larger/different neighborhoods, or persistent adaptation are impossible.','', 'Earlier threshold propagation v1 and probability/moment v2 completed before the latest route change; both remain separately marked superseded. Their respective corruption union gains2.1408/2.0765pp are real development results, but teacher-target-generated candidates do not satisfy the latest student-only support constraint. Do not rewrite them as uniformly failed regression.','', 'Future S1 would freeze student-generated candidates, use Sa2VA only for scalar preferences, and update persistent parameters by Reverse-KL of a finite-support compatibility softmax. This compatibility is a proposed surrogate distribution, not an established native likelihood or measured online-TTA gain. No temporal OPD rescue or production promotion.','', '## Verification and resources','',f"GPU process {res['gpu_process_seconds']:.2f}s;864 suffix candidate evaluations and2 nonzero-state full-native reinsertion checks;0 new experts,0 backward,0 H captures,0 GPU failures.96 exact native checks,1440 dual metric calls,3 CPU contracts,independent NumPy parameter support checks and public scalar/CI reconstruction. First summary serialization encountered NumPy int64 counts after metric computation; explicit Python-int conversion fixed it, CPU rescoring matched existing ROWS exactly, original log retained and no GPU rerun. See SCORING_RECOVERY.json.",'']
    (OUT/'REPORT.md').write_text('\n'.join(lines));write(OUT/'DECISION.json',dict(status='completed',measurement='audited',claim='Limited positive native rollout support, insufficient enlargement in this fixed parameter neighborhood',S1_started=False,OPD_run=False,online_learning_run=False,production_changed=False,decision='Finish this support screen; no automatic radius/direction search or S1',scope='9 candidates,4 antithetic orthogonal directions,.05 parameter L2 radius,16 exposed sources',negative_scope='Does not establish universal spatial OPD impossibility'))
    print({g:{k:s[g]['metrics'][k]['mean'] for k in ['rollout_gain','union_gain','matched12_unobserved_gain']} for g in ['corruption','clean']})

if __name__=='__main__':run()
