"""Render S0 results without promoting oracle support to deployment success."""
import sys,collections,time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from scripts.decota_matrix_common_v1 import read,write,sha
from scripts.run_tastvg_spatial_expansion_s0_v1 import OUT
from scripts.audit_tastvg_spatial_expansion_public_v1 import run as audit

def run():
    s=read(OUT/'SUMMARY.json');rows=read(OUT/'ROWS.json');alloc=[read(f) for f in sorted((OUT/'allocations').glob('*.json'))]
    resource=dict(gpu_process_seconds=sum(x['seconds'] for x in alloc),by_stage={k:sum(x['seconds'] for x in alloc if x['stage']==k) for k in sorted({x['stage'] for x in alloc})},allocations=len(alloc),failures=[x for x in alloc if x['status']=='failed'],expert_new_calls=sum(not r['reused'] for r in rows),expert_reuse_cells=sum(r['reused'] for r in rows),trajectory_backward_calls=288,verification_replay_backward_calls=read(OUT/'REINSERTION_AUDIT.json')['additional_replay_backward_calls'],download_setup=read(OUT/'DOWNLOAD_SETUP_RECEIPT.json'),download=read(ROOT/'checkpoints/Sa2VA-4B/DOWNLOAD_RECEIPT.json'))
    write(OUT/'RESOURCES.json',resource);write(OUT/'PUBLIC_AUDIT.json',audit(OUT))
    setup=read(OUT/'EXPERT_SETUP.json');lock=read(OUT/'LOCK.json')
    write(OUT/'PROVENANCE.json',dict(backbone='TA-STVG',source_model_state_sha256=read(ROOT/'artifacts/tastvg_transient_c25_c3_c06_v1/CAPTURE_BARRIER.json')['model_state_sha256'],expert=setup,cohort='Original C3 first16 previously exposed VidSTG sources, one query each',conditions=lock['conditions'],sources=16,cells=96,GT_scope='16 old exposed keys; scoring only after prediction seal',implementation_sha256={f:sha(ROOT/f) for f in ['vg_tta/tastvg_spatial_expansion_s0_v1.py','scripts/run_tastvg_spatial_expansion_s0_v1.py','scripts/score_tastvg_spatial_expansion_s0_v1.py']},production_changed=False))
    pp=lambda v:'NA' if v is None else f'{100*v:.4f}'
    ci=lambda v:'NA' if v['ci95'] is None else '['+', '.join(pp(x) for x in v['ci95'])+']'
    lines=['# S0: Sa2VA-guided spatial hypothesis expansion','', 'Completed / independently audited. This is an offline candidate-support diagnostic, not a learned or deployed selector. Temporal research remains native-candidate + UniversalVTG reranking; no new temporal run or OPD rescue.','', '| Condition | Native sIoU % | Native six-layer oracle % | RVOS trajectory oracle % | Expansion gain pp | 95% source CI pp | Expansion minus six-layer pp |','|---|---:|---:|---:|---:|---|---:|']
    for c,x in s.items():
        m=x['metrics'];lines.append(f"| {c} | {pp(m['native_s']['mean'])} | {pp(m['six_layer_oracle_s']['mean'])} | {pp(m['expanded_oracle_s']['mean'])} | {pp(m['expanded_gain']['mean'])} | {ci(m['expanded_gain'])} | {pp(m['expanded_minus_six_layer']['mean'])} |")
    lines+=['','## Configuration and denominator','', 'Original C3 first16 historically exposed VidSTG target-test sources, one query/source. Clean + five existing source-hash seed0 5% transient corruptions:96 cells. Corruption primary averages five conditions within source, then16 sources; paired10000-source bootstrap. Clean is separate. This is development evidence. The historical +0.705pp six-layer result used different conditions; only the matched comparator above is used.','', 'Official Sa2VA-4B revision3fee777d49ee9276eac51ea3e5f9b69e81d09be6, BF16/eager, greedy256-token cap. Five uniformly sampled observed frames per video, original caption prompt, first SEG mask only. Sparse nonempty mask-derived boxes guide checkpoint-weighted L1/GIoU on observed positions. Exactly3 normalized H_app-only steps of .004 original combined visual-H norm, total<=.012. Text/motion/weights remain frozen; official detach and dynamic native routing retained. Native B0 plus B1/B2/B3 retained, no backtracking/GT-guided optimization or intermediate stopping.','', 'All96 trajectories sealed before16 previous GT keys loaded. The oracle selects one entire tube among four, then evaluates sIoU over all GT-valid sampled frames, not frame-wise GT mixture or temporal intersection. Direct sparse expert quality has a different observed-frame denominator. Cached suffix reuses exact native H; no backbone per gradient step.','', '## Evidence and trajectory diagnostics','', '| Group | Nonempty cells | Valid evidence frames / sampled | Unique expert calls | Best step counts 0/1/2/3 | Step3 gain pp | Step3 harms >5pp |','|---|---:|---:|---:|---|---:|---:|']
    for c in ['corruption','clean']:
        x=s[c];cv=x['coverage'];lines.append(f"| {c} | {cv['nonempty_cells']}/{x['cells']} | {cv['valid_frames']}/{cv['sampled_frames']} | {x['cells']-cv['reused']} | {'/'.join(str(x['chosen_step'].get(str(j),0)) for j in range(4))} | {pp(x['metrics']['step3_gain']['mean'])} | {x['step3_harms_gt5pp']} |")
    for c in ['corruption','clean']:
        m=s[c]['metrics'];lines+=['',f"{c}: oracle gain outside the five observed positions {pp(m['unobserved_gain_at_s_oracle']['mean'])}pp; on observed valid positions {pp(m['observed_gain_at_s_oracle']['mean'])}pp. Direct RVOS evidence sIoU {pp(m['expert_observed_s']['mean'])}% versus native {pp(m['native_expert_observed_s']['mean'])}% on the same nonempty-evidence/GT-valid positions. Oracle union with six-layer candidates adds {pp(m['union_minus_six_layer']['mean'])}pp over six-layer. s-oracle-selected native tube vIoU change {pp(m['v_gain_at_s_oracle']['mean'])}pp with its dynamic temporal output; this is diagnostic, not final temporal reranking."]
    decreasing=sum(r['diagnostics'][-1]['loss_after']<r['diagnostics'][0]['loss_before'] for r in rows)
    lines+=['',f"Alignment loss decreases from B0 to B3 in {decreasing}/96 cells. Zero oracle harm is structural because B0 is retained; it does not prove online selection safety. Individual-step scores and negatives remain in ROWS.json. No clean-specific tuning, severity adjustment, additional seeds, selector, spatial OPD or online state was run.",'','## Verification and resources','',f"GPU-process time {resource['gpu_process_seconds']:.2f}s, including load/setup failures; stage totals {resource['by_stage']}. New expert calls {resource['expert_new_calls']}; exact sparse-observation cache reuses {resource['expert_reuse_cells']}.288 native suffix gradient steps. Model weight download is separate CPU/network setup. AUDIT.json records exact native replay, whole-pipeline reinsertion, independent loss/mask/dual task metrics; PUBLIC_AUDIT.json independently reconstructs scalar oracles and bootstrap summaries. Three CPU tests cover mask geometry, empty evidence and independent loss/gradient.",'','No production method changes. S1 is a possible next experiment only; S0 oracle support cannot establish critic ranking, OPD transfer, online-TTA gains or a publishable end-to-end method.','', '[Official expert model](https://huggingface.co/ByteDance/Sa2VA-4B), [official implementation](https://github.com/bytedance/Sa2VA).','']
    (OUT/'REPORT.md').write_text('\n'.join(lines))

if __name__=='__main__':run()
